##########################
## Site Config Settings ##
##########################

# Theme version
version: 1.1.0

# Header
menu:
  - page: home
    directory: .
    icon: fa-home
  - page: about
    directory: about/about.html
    icon: fa-user
  - page: plugins
    directory: about/hexo.html
    icon: fa-hexo

# Sidebar
widgets:
  - notify
  - category
  - tag
  #- archive
  #- weibo
  - links

# Toc
toc:
  enable: true
  number: false

# Static files
js: static/js
css: static/css

# Date_formats
date_formats:
  archive: "MM月DD日"
  category: "YYYY/MM/DD"
  post: "YYYY年MM月DD日"
  tag: "YYYY/MM/DD"

#Local search
local_search: true ## Use a javascript-based local search engine, true/false.

#Cmments
comment:
  disqus: ## disqus_shortname
  livere: ## 来必力(data-uid)
  changyan: ## 畅言需在下方配置两个参数，此处不填。
    appid: cytGciV2d ## 畅言(appid)
    appkey: 3a4e594fd4d0210ddd7489c703cc8f7f ##畅言(appkey)

#Share
baidu_share: false ##百度分享
addToAny_share: # AddToAny share. Empty list hides. List items are service name at url. For ex: email for '<a href="https://www.addtoany.com/add_to/email?linkurl=...'

# Analytics
google_analytics: ## Your Google Analytics tracking id, e.g. UA-42025684-2
baidu_analytics: ## Your Baidu Analytics tracking id, e.g. 1006843030519956000
umeng_analytics: 1263161803 ## Your Umeng Analytics tracking id, e.g. 1263161802

# Miscellaneous
show_category_count: true ## If you want to show the count of categories in the sidebar widget please set the value to true.
widgets_on_small_screens: true ## Set to true to enable widgets on small screens.
busuanzi: false ##访问量计数http://busuanzi.ibruce.info/

notify:
  - title: 1、欢迎来到云腾博客。
    url:

links:
  - title: 云腾网
    url: http://www.crise.cn/
  - title: BlueLake
    url: https://github.com/chaooo/hexo-theme-BlueLake
